### ISSUE TITLE
Endianness

### ISSUE THREAD

**Issue by LPGhatguy** [BVE-Reborn/shader-types#4]
Does this crate need to worry about endianness of the host machine? I'm not sure how many Rust graphics developers are running on big endian host machines with little endian GPUs, but that seems like it could be in the problem domain of shader-types.

**Comment by cwfitzgerald** [comment]
As far as I know, vulkan/ogl guarantee that the endianness of the gpu match the endianness of the cpu, so this should be fine and we shouldn't need to worry about it.

Also who uses big endian...
